Fixed links
pi-hole/docs pull request #425
Opened 2020-12-02 14:12 UTC by rosscg

**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [ x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x ] I have made only one major change in my proposed changes.
- [ x] I have commented my proposed changes within the code.
- [ x] I have tested my proposed changes, and have included unit tests where possible.
- [ x] I am willing to help maintain this change if there are issues with it later.
- [ x] I give this submission freely and claim no ownership.
- [ x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [ x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
*A detailed description, screenshots (if necessary), as well as links to any relevant GitHub issues*

**How does this PR accomplish the above?:**
*A detailed description (such as a changelog) and screenshots (if necessary) of the implemented fix*

**What documentation changes (if any) are needed to support this PR?:**
*A detailed list of any necessary changes*

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

2020-12-02 17:32 UTC, dschaper requested changes

2020-12-02 17:32 UTC, dschaper commented on docs/guides/vpn/overview.md
> +If you don't want a full-tunnel, we provide a page of how to [set up your server to exclusively route DNS traffic, but nothing else via the VPN](vpn/only-dns-via-vpn.md). On another optional page, we
Same here, there are no `vpn/only-dns-via-vpn.md` files.

2020-12-02 17:53 UTC, PromoFaux commented on docs/guides/vpn/overview.md
Just checked on the main docs page.. the links seem to be OK anyway...

![image](https://user-images.githubusercontent.com/1998970/100911547-4bd02300-34c7-11eb-9c5f-c3a5a40da1e0.png)


![image](https://user-images.githubusercontent.com/1998970/100911496-3824bc80-34c7-11eb-9022-177e7f40b233.png)

2020-12-02 17:59 UTC, dschaper commented on docs/guides/vpn/overview.md
Which link seems to be okay?

2020-12-02 18:06 UTC, PromoFaux commented on docs/guides/vpn/overview.md
All the ones the PR is seemingly trying to address. I'm not sure what is broken about them that needs fixing.

2020-12-02 18:08 UTC, PromoFaux commented on docs/guides/vpn/overview.md
![things that work](https://user-images.githubusercontent.com/1998970/100913236-67d4c400-34c9-11eb-972a-2443d7934d27.gif)

2020-12-10 13:32 UTC, rosscg commented on docs/guides/vpn/overview.md
You are right, I'm not sure what was causing the problem I experienced as I now cannot replicate it.

2020-12-10 13:32 UTC, rosscg commented
You are right, I'm not sure what was causing the problem I experienced as I now cannot replicate it.

2020-12-10 13:32 UTC, closed without merging