Update the unspecified IP blocking documentation
pi-hole/docs pull request #687
Opened 2022-04-07 08:32 UTC by farcaller

**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/contributing/).

---
**What does this PR aim to accomplish?:**
Update the documentation reflecting 0.0.0.0 being treated like 127.0.0.1 in some cases. This behavior can trigger in a bunch of networking stacks, e.g. Zoom on macOS will try to connect to a local webserver if some zoom urls are blocked. Similarly, most of Synology's software running on Linux will try to do the same.

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

2022-08-14 05:38 UTC, DL6ER requested changes
Sorry for the long delay in reviewing. I made two small change suggestions, what do you think? NULL still seems to be the best "universal" solution we have at hand, we shouldn't be too negative about it

2022-08-14 05:38 UTC, DL6ER commented on docs/ftldns/blockingmode.md
> +- Some networking stacks and applications might treat 0.0.0.0 as if it was 127.0.0.1 and try to connect to a local webserver if one's running; causing various connectivity issues
```suggestion
- Some networking stacks and applications might treat `0.0.0.0` as if it was `127.0.0.1` and try to connect to a local webserver if one's running; possibly causing connectivity issues
```

2022-08-14 05:38 UTC, DL6ER commented on docs/ftldns/blockingmode.md
>  - No need to run a web server on your Pi-hole (reduces complexity when running other web services on the same machine)
```suggestion
- Solves potential HTTPS timeouts as requests may never be performed (depending on your system)
- No need to run a web server on your Pi-hole (reduces complexity when running other web services on the same machine)
```

2022-08-14 09:59 UTC, farcaller commented
> Sorry for the long delay in reviewing. I made two small change suggestions, what do you think? NULL still seems to be the best "universal" solution we have at hand, we shouldn't be too negative about it

Yeah, with a caveat of "depends on your OS" 😄

2023-01-06 10:00 UTC, closed without merging

2023-01-06 14:54 UTC, farcaller commented
derp, it's not like I get email notifications for labels...

2023-01-06 15:01 UTC, farcaller commented
...but it looks like this was already merged in with a similar wording either way, so no point in rebasing.