Add requirement of nftables to wireguard config
pi-hole/docs pull request #690
Opened 2022-04-18 22:24 UTC by CleanMachine1

This PR adds a command which maybe not installed on a users computer, this command installs the dependency.

**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [] I have commented my proposed changes within the code.
- [ ] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/contributing/).

---
**What does this PR aim to accomplish?:**
*A detailed description, screenshots (if necessary), as well as links to any relevant GitHub issues*

Fixing a dependency issue which will cause it not to function if nftables is not installed.

**How does this PR accomplish the above?:**
*A detailed description (such as a changelog) and screenshots (if necessary) of the implemented fix*

By adding a recommendation to install it, giving the command for the user to copy

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed. :+1: 
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time. :+1:

2022-04-18 22:37 UTC, CleanMachine1 commented
I based this PR off of https://github.com/pi-hole/docs/blob/c958a69a2e5a3d48d11e61bf7b0373fcae184426/docs/guides/vpn/wireguard/client.md?plain=1#L202

2022-04-19 05:22 UTC, DL6ER approved these changes

2022-04-19 05:35 UTC, yubiuser requested changes
The tests are failing because of

```
docs/guides/vpn/wireguard/internal.md:51:1 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 4]
Summary: 1 error(s)
```

2022-04-19 15:31 UTC, CleanMachine1 commented
I am going to create a new PR since I do not have the expertise to fix this. I rebased however made a mistake leading to other things being merged. Sorry for this mistake.

2022-04-19 15:31 UTC, closed without merging