Add interfaces API endpoint documentation
pi-hole/docs pull request #727
Opened 2022-06-19 20:55 UTC by yubiuser

Documentation for https://github.com/pi-hole/FTL/pull/1355

2022-06-20 20:03 UTC, DL6ER approved these changes

2022-06-20 20:55 UTC, rdwebdesign reviewed
I have a **suggestion**:

Currently, this page uses List Items to show each API endpoint, like this:

```
- `>endpoint1`: explanation

    ```text
    output of endpoint1
    ```
```

I think we could replace the list items with Headings, like this:

```
    ## `>endpoint1`:
    explanation
    ```text
    output of endpoint1
    ```

    ## `>endpoint2`:
    Explanation 2
    ```text
    output of endpoint2
    ```
```

Using Headings the endpoints would be listed in the "Table of contents" sub-menu.

2022-06-21 21:00 UTC, yubiuser commented
Force pushed to adhere the new heading style from https://github.com/pi-hole/docs/pull/729

2022-06-21 21:00 UTC, yubiuser commented
Needs re-approval.

2022-06-21 21:37 UTC, rdwebdesign requested changes

2022-06-21 21:37 UTC, rdwebdesign commented on docs/ftldns/telnet-api.md
> +#### `>interfaces` {data-toc-label='interfaces'}
You need to add the 
```

---

```

before the new `>interfaces` item.

2022-06-22 06:59 UTC, rdwebdesign approved these changes

2022-07-07 21:35 UTC, merged