Fritz!Box: assign DNS real-time priority and block bypassing DNS traffic
pi-hole/docs pull request #827
Opened 2022-12-29 17:35 UTC by DL6ER

**What does this PR aim to accomplish?:**

Extend FritzBox guide: 
1. make DNS a realtime-service. This assigns priority when the connection is completely used, e.g. by a running download and,
2. add filter (= firewall) instructions to block port 53/UDP for devices in your local network except the Pi-hole

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
5. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
6. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
7. I have checked that another pull request for this purpose does not exist.
8. I have considered, and confirmed that this submission will be valuable to others.
9. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
10. I give this submission freely, and claim no ownership to its content.

---
- [X] I have read the above and my PR is ready for review. *Check this box to confirm*

2022-12-29 17:35 UTC, DL6ER commented
This has been confirmed working on a locally available Fritz!Box 7590

2022-12-29 22:06 UTC, yubiuser reviewed
Why did you only include `UDP`and not also `TCP` as protocol?

2022-12-29 22:06 UTC, yubiuser commented on docs/routers/fritzbox.md
> +Since all settings go through the Pi-hole, select this as the device to which the rule should apply. If you are unsure, "`All devices`" may also be useful selection here. As "`Network Application`" s
```suggestion
Select your Pi-hole devices as the device to which the rule should apply. If you are unsure, "`All devices`" may also be useful selection here. As "`Network Application`" select the "`DNS`" entry you just created.
```

2022-12-29 22:06 UTC, yubiuser commented on docs/routers/fritzbox.md
> +In the profile "`Standard`" add the network application "`DNS`" created above under:
```suggestion
In the profile "`Standard`" add the network application "`DNS`" (created above in `Optional: Increasing the priority of DNS requests`) under:
```

2022-12-29 22:06 UTC, yubiuser commented on docs/routers/fritzbox.md
> +
```suggestion

!!! warning
    Some devices or applications use hard-coded DNS servers and won't work reliable if they can't be reached. If you observe such behavior you need to remove the affected device from the list of blocked devices. 
    
```

2022-12-30 08:19 UTC, DL6ER commented
Squashed insignificant commits and rebased on latest `master`

2022-12-30 10:56 UTC, yubiuser requested changes

2022-12-30 10:56 UTC, yubiuser commented on docs/routers/fritzbox-de.md
> +Netzwerkanwendung: TCP
```suggestion
Netzwerkanwendung: DNS
```

2022-12-30 10:56 UTC, yubiuser commented on docs/routers/fritzbox-de.md
> +Protokoll: UDP
```suggestion
Protokoll: TCP
```

2022-12-30 10:56 UTC, yubiuser commented on docs/routers/fritzbox-de.md
> +    Einige Geräte oder Programme nutzen fest hinterlegte DNS Server und funktionieren ggfs. nicht mehr ordnungsgemäß falls sie diesen DNS Server nicht erreichen können. Fall solch ein Verhalten auftr
```suggestion
    Einige Geräte oder Programme nutzen fest hinterlegte DNS Server und funktionieren ggfs. nicht mehr ordnungsgemäß falls sie diesen DNS Server nicht erreichen können. Fall solch ein Verhalten auftritt, können Sie dieses Gerät von der Filterregel ausnehmen.
```

2022-12-30 10:56 UTC, yubiuser commented on docs/routers/fritzbox.md
> +    Some devices or applications use hard-coded DNS servers and may not work as expected if they can't be reached. If you observe such behavior, you can easily remove the affected device from this fi
```suggestion
    Some devices or applications use hard-coded DNS servers and may not work as expected if they can't  reach the desired DNS server. If you observe such behavior, you can easily remove the affected device from this filter.
```

2022-12-30 10:56 UTC, yubiuser commented on docs/routers/fritzbox-de.md
> +die wie unter `Optional: Erhöhung der Priorität von DNS Anfragen` beschrieben angelegte Netzwerkanwendung "`DNS`" hinzu.
```suggestion
die [angelegte Netzwerkanwendung "`DNS`"](/routers/fritzbox-de/#optional-erhohung-der-prioritat-von-dns-anfragen) hinzu.
```

2022-12-30 10:56 UTC, yubiuser commented on docs/routers/fritzbox.md
> +In the profile "`Standard`" add the network application "`DNS`" (created above in `Optional: Increasing the priority of DNS requests`) under:
```suggestion
In the profile "`Standard`" add the network application "`DNS`" ([created above](/routers/fritzbox/#optional-increasing-the-priority-of-dns-requests)) under:
```

2022-12-30 11:04 UTC, yubiuser approved these changes

2022-12-30 11:04 UTC, merged